!!python/object/new:easydict.EasyDict
dictitems:
  FILEIO: &id006 !!python/object/new:easydict.EasyDict
    dictitems:
      DATASET_DIR: C:\Users\212769892\serviceBot\datasets
      LOG_DIR: C:\Users\212769892\serviceBot\logs
      PROJECT_DIR: C:\Users\212769892\serviceBot
      YAML_CONFIG: c:\Users\212769892\serviceBot\config\base_config.yaml
    state:
      DATASET_DIR: C:\Users\212769892\serviceBot\datasets
      LOG_DIR: C:\Users\212769892\serviceBot\logs
      PROJECT_DIR: C:\Users\212769892\serviceBot
      YAML_CONFIG: c:\Users\212769892\serviceBot\config\base_config.yaml
  MODEL: &id007 !!python/object/new:easydict.EasyDict
    dictitems:
      BACKBONE: resnet101
      FRAMEWORK: tensorflow
      NAME: ''
      RESNET: &id005 !!python/object/new:easydict.EasyDict
        dictitems:
          FILTERS_C2: &id001
          - 64
          - 64
          - 256
          FILTERS_C3: &id002
          - 128
          - 128
          - 512
          FILTERS_C4: &id003
          - 256
          - 256
          - 1024
          FILTERS_C5: &id004
          - 512
          - 512
          - 2048
        state:
          FILTERS_C2: *id001
          FILTERS_C3: *id002
          FILTERS_C4: *id003
          FILTERS_C5: *id004
    state:
      BACKBONE: resnet101
      FRAMEWORK: tensorflow
      NAME: ''
      RESNET: *id005
  TRAIN: &id008 !!python/object/new:easydict.EasyDict
    dictitems:
      BATCH_SIZE: 32
      LEARNING_MOMENTUM: 0.9
      LEARNING_RATE: 0.001
      LEARNING_WEIGHT_DECAY: 0.0001
      NB_EPOCH: 10
      NB_GPUS: 1
      OPTIMIZER: adam
      PRINT_FREQ: 100
      RESUME: false
      SHUFFLE: true
      USE_GPU: true
    state:
      BATCH_SIZE: 32
      LEARNING_MOMENTUM: 0.9
      LEARNING_RATE: 0.001
      LEARNING_WEIGHT_DECAY: 0.0001
      NB_EPOCH: 10
      NB_GPUS: 1
      OPTIMIZER: adam
      PRINT_FREQ: 100
      RESUME: false
      SHUFFLE: true
      USE_GPU: true
state:
  FILEIO: *id006
  MODEL: *id007
  TRAIN: *id008
