DATASET:
  IMAGE_CHANNELS: 3
  IMAGE_SIZE:
  - 224
  - 224
  NB_CLASSES: 2
FILEIO:
  CONFIG_YAML: untitled.yaml
  LOG_DIR: /home/phatluu/serviceBot/logModels
  PROJECT_DIR: /home/phatluu/serviceBot
HARDWARE:
  GPU_COUNT: 1
MODEL: !!python/object/new:easydict.EasyDict
  dictitems:
    BACKBONE: resnet101
    FRAMEWORK: tensorflow
    NAME: resnet50
    RESNET: &id005 !!python/object/new:easydict.EasyDict
      dictitems:
        FILTERS_C2: &id001
        - 64
        - 64
        - 256
        FILTERS_C3: &id002
        - 128
        - 128
        - 512
        FILTERS_C4: &id003
        - 256
        - 256
        - 1024
        FILTERS_C5: &id004
        - 512
        - 512
        - 2048
      state:
        FILTERS_C2: *id001
        FILTERS_C3: *id002
        FILTERS_C4: *id003
        FILTERS_C5: *id004
  state:
    BACKBONE: resnet101
    FRAMEWORK: tensorflow
    NAME: resnet50
    RESNET: *id005
TRAIN:
  BATCH_SIZE: 32
  LEARNING_MOMENTUM: 0.9
  LEARNING_RATE: 0.001
  LEARNING_WEIGHT_DECAY: 0.0001
  NB_EPOCH: 10
  OPTIMIZER: adam
  PRINT_FREQ: 100
  RESUME: false
  SHUFFLE: true
